### ISSUE TITLE
Reverse resolver?

### ISSUE THREAD

**Issue by FredyC** [with-heart/apollo-link-response-resolver#17]
Hey, thanks for the lib and mainly the idea. I am currently trying to solve the automatic conversion of ISO date formats so I can always work with `Date` instance in the app. It seems impossible with ApolloClient, so it's great it can be done like this with the Link.

Now to just figure the opposite direction when I am calling mutation I would like to have `Date` converted back to ISO. I will definitely try to solve it on my own, shouldn't be that hard. I just wonder if you have attempted something like that and stumbled into some issues with it.

**Comment by with-heart** [comment]
Hi @FredyC! I actually haven't used this library in quite awhile, and no longer think it's necessary. See #18 for more info. Sorry I can't be of more help!
